### PR TITLE
[#121] Run (.stop client) in different thread from p/catch

### PR DESCRIPTION
**Pull request by ghaskins**
Fixes Issue #121

### CODE REVIEW

**Comment by sundbry** [comment]
Looks like you found a deadlock. Explains why nobody in Jetty noticed anything. LGTM!

**Review by ecb — APPROVED** [review]
good find

**Comment by ghaskins** [comment]
@sundbry yeah, it was specific to how protojure was using jetty+promesa.  Ill cut a new release with this and your TE patch

**Comment by ghaskins** [comment]
@sundbry https://github.com/protojure/lib/releases/tag/v2.0.7

**Pull request merged**
